// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvoetcozxunkuxuxzajm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2b2V0Y296eHVua3V4dXh6YWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTY0NzEsImV4cCI6MjA3MDgzMjQ3MX0.iHYkighRHFOVsNTbyM4olJkLIke7_PnMCSqYRIgFaT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});